version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "yourcat-dev"
s3_bucket = "dev-sam-artifactstore"
s3_prefix = "yourcat-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = """\
    EnvironmentName=\"dev\" \
"""
tags = "project=\"YourCat\" CloudFormation=\"true\""
confirm_changeset = false

[prd]
[prd.deploy]
[prd.deploy.parameters]
stack_name = "yourcat-prd"
s3_bucket = "prd-sam-artifactstore"
s3_prefix = "yourcat-prd"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = """\
    EnvironmentName=\"prd\" \
"""
tags = "project=\"YourCat\" CloudFormation=\"true\""
confirm_changeset = false
