version = 0.1

[prd]
[prd.deploy]
[prd.deploy.parameters]
stack_name = "photocat-prd"
s3_bucket = "common-prd-sam-artifactstore"
s3_prefix = "photocat-prd"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = """\
    EnvironmentName=\"prd\" \
    ApiAllowOrigin=\"https://kei.ooo\" \
"""
tags = "project=\"photocat\" env=\"prd\" IaC=\"cfn\""
confirm_changeset = false
